markdown: rdiscount
permalink: /posts/:title
rdiscount:
  extensions: [smart]

gems:
  - jekyll-sitemap

name: Sean Mertens
url: http://codinggenius.github.io
description: A fantastic blog that is fantastic.
